CREATE SCHEMA IF NOT EXISTS sap_raw;
CREATE SCHEMA IF NOT EXISTS hcm_core;
CREATE SCHEMA IF NOT EXISTS hcm_service;
CREATE SCHEMA IF NOT EXISTS hcm_security;
CREATE SCHEMA IF NOT EXISTS hcm_integration;
CREATE SCHEMA IF NOT EXISTS hcm_audit;
CREATE SCHEMA IF NOT EXISTS hcm_analytics;
