-- SAP-aligned BASE layer. Keep source names/keys; extend field lists from target DDIC extracts.

CREATE TABLE IF NOT EXISTS sap_raw.pa0000 (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  begda date NOT NULL,
  endda date NOT NULL,
  massn varchar(2),
  massg varchar(2),
  stat1 varchar(1),
  stat2 varchar(1),
  stat3 varchar(1),
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PA0000',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, begda, endda, massn, massg)
);

CREATE TABLE IF NOT EXISTS sap_raw.pa0001 (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  begda date NOT NULL,
  endda date NOT NULL,
  bukrs varchar(4),
  werks varchar(4),
  btrtl varchar(4),
  persg varchar(1),
  persk varchar(2),
  kostl varchar(10),
  plans varchar(8),
  stell varchar(8),
  orgeh varchar(8),
  sachp varchar(3),
  sachz varchar(3),
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PA0001',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.pa0002 (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  begda date NOT NULL,
  endda date NOT NULL,
  nachn varchar(40),
  vorna varchar(40),
  name2 varchar(40),
  gbdat date,
  gesch varchar(1),
  famst varchar(1),
  natio varchar(3),
  anred varchar(15),
  gbort varchar(40),
  gbdep varchar(3),
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PA0002',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.pa0006 (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  subty varchar(4) NOT NULL,
  objps varchar(2) NOT NULL,
  sprps varchar(1) NOT NULL,
  endda date NOT NULL,
  begda date NOT NULL,
  anssa varchar(15),
  stras varchar(60),
  ort01 varchar(40),
  pstlz varchar(10),
  land1 varchar(3),
  telnr varchar(30),
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PA0006',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, subty, objps, sprps, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.pa0021 (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  subty varchar(4) NOT NULL,
  objps varchar(2) NOT NULL,
  sprps varchar(1) NOT NULL,
  endda date NOT NULL,
  begda date NOT NULL,
  favor varchar(40),
  fanam varchar(40),
  fgbdt date,
  famsa varchar(4),
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PA0021',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, subty, objps, sprps, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.pa0022 (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  subty varchar(4) NOT NULL,
  objps varchar(2) NOT NULL,
  sprps varchar(1) NOT NULL,
  endda date NOT NULL,
  begda date NOT NULL,
  slart varchar(4),
  insti varchar(100),
  fachr varchar(100),
  ausbi varchar(4),
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PA0022',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, subty, objps, sprps, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.pa0024 (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  subty varchar(4) NOT NULL,
  objps varchar(2) NOT NULL,
  sprps varchar(1) NOT NULL,
  endda date NOT NULL,
  begda date NOT NULL,
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PA0024',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, subty, objps, sprps, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.pa0007 (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  begda date NOT NULL,
  endda date NOT NULL,
  schkz varchar(2),
  empct numeric(5,2),
  mostd numeric(7,2),
  wostd numeric(7,2),
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PA0007',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.pa0008 (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  subty varchar(4) NOT NULL,
  objps varchar(2) NOT NULL,
  sprps varchar(1) NOT NULL,
  endda date NOT NULL,
  begda date NOT NULL,
  trfar varchar(2),
  trfgb varchar(3),
  trfgr varchar(3),
  trfst varchar(2),
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PA0008',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, subty, objps, sprps, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.pa0014 (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  subty varchar(4) NOT NULL,
  objps varchar(2) NOT NULL,
  sprps varchar(1) NOT NULL,
  endda date NOT NULL,
  begda date NOT NULL,
  lgart varchar(4) NOT NULL,
  betrg numeric(18,2),
  waers varchar(5),
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PA0014',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, subty, objps, sprps, begda, endda, lgart)
);

CREATE TABLE IF NOT EXISTS sap_raw.pa0015 (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  subty varchar(4) NOT NULL,
  objps varchar(2) NOT NULL,
  sprps varchar(1) NOT NULL,
  endda date NOT NULL,
  begda date NOT NULL,
  lgart varchar(4) NOT NULL,
  betrg numeric(18,2),
  waers varchar(5),
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PA0015',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, subty, objps, sprps, begda, endda, lgart)
);

CREATE TABLE IF NOT EXISTS sap_raw.pa0045 (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  subty varchar(4) NOT NULL,
  objps varchar(2) NOT NULL,
  sprps varchar(1) NOT NULL,
  endda date NOT NULL,
  begda date NOT NULL,
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PA0045',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, subty, objps, sprps, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.pa2001 (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  subty varchar(4) NOT NULL,
  objps varchar(2) NOT NULL,
  sprps varchar(1) NOT NULL,
  endda date NOT NULL,
  begda date NOT NULL,
  awart varchar(4),
  abwtg numeric(7,2),
  abwtb numeric(7,2),
  beguz time,
  enduz time,
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PA2001',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, subty, objps, sprps, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.pa2002 (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  subty varchar(4) NOT NULL,
  objps varchar(2) NOT NULL,
  sprps varchar(1) NOT NULL,
  endda date NOT NULL,
  begda date NOT NULL,
  awart varchar(4),
  stdaz numeric(7,2),
  beguz time,
  enduz time,
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PA2002',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, subty, objps, sprps, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.pa2005 (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  subty varchar(4) NOT NULL,
  objps varchar(2) NOT NULL,
  sprps varchar(1) NOT NULL,
  endda date NOT NULL,
  begda date NOT NULL,
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PA2005',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, subty, objps, sprps, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.pa2006 (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  subty varchar(4) NOT NULL,
  objps varchar(2) NOT NULL,
  sprps varchar(1) NOT NULL,
  endda date NOT NULL,
  begda date NOT NULL,
  ktart varchar(2),
  anzhl numeric(9,2),
  kverb numeric(9,2),
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PA2006',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, subty, objps, sprps, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.pa2007 (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  subty varchar(4) NOT NULL,
  objps varchar(2) NOT NULL,
  sprps varchar(1) NOT NULL,
  endda date NOT NULL,
  begda date NOT NULL,
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PA2007',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, subty, objps, sprps, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.hrp1000 (
  mandt varchar(3) NOT NULL,
  otype varchar(2) NOT NULL,
  objid varchar(8) NOT NULL,
  istat varchar(1) NOT NULL,
  begda date NOT NULL,
  endda date NOT NULL,
  short varchar(40),
  stext varchar(120),
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'HRP1000',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, otype, objid, istat, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.hrp1001 (
  mandt varchar(3) NOT NULL,
  otype varchar(2) NOT NULL,
  objid varchar(8) NOT NULL,
  plvar varchar(2),
  rsign varchar(1),
  relat varchar(3),
  sclas varchar(2),
  sobid varchar(8),
  begda date NOT NULL,
  endda date NOT NULL,
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'HRP1001',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, otype, objid, rsign, relat, sclas, sobid, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.pa0041 (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  subty varchar(4) NOT NULL DEFAULT '',
  objps varchar(2) NOT NULL DEFAULT '',
  sprps varchar(1) NOT NULL DEFAULT '',
  endda date NOT NULL,
  begda date NOT NULL,
  dar01 varchar(2),
  dat01 date,
  dar02 varchar(2),
  dat02 date,
  dar03 varchar(2),
  dat03 date,
  dar04 varchar(2),
  dat04 date,
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PA0041',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, subty, objps, sprps, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.pa0016 (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  subty varchar(4) NOT NULL DEFAULT '',
  objps varchar(2) NOT NULL DEFAULT '',
  sprps varchar(1) NOT NULL DEFAULT '',
  endda date NOT NULL,
  begda date NOT NULL,
  cttyp varchar(2),
  ctnum varchar(20),
  ctbeg date,
  ctend date,
  kdgfr varchar(3),
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PA0016',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, subty, objps, sprps, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.pa0028 (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  subty varchar(4) NOT NULL,
  objps varchar(2) NOT NULL DEFAULT '',
  sprps varchar(1) NOT NULL DEFAULT '',
  endda date NOT NULL,
  begda date NOT NULL,
  examd date,
  examm varchar(4),
  resul varchar(2),
  diagn text,
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PA0028',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, subty, objps, sprps, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.hrp1002 (
  mandt varchar(3) NOT NULL,
  plvar varchar(2) NOT NULL DEFAULT '01',
  otype varchar(2) NOT NULL,
  objid varchar(8) NOT NULL,
  subty varchar(4) NOT NULL,
  istat varchar(1) NOT NULL DEFAULT '1',
  begda date NOT NULL,
  endda date NOT NULL,
  tformat varchar(2),
  tline text,
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'HRP1002',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, plvar, otype, objid, subty, istat, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.teven (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  ldate date NOT NULL,
  ltime time NOT NULL,
  satza varchar(3) NOT NULL,
  terid varchar(4),
  abwgr varchar(4),
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'TEVEN',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, ldate, ltime, satza)
);

CREATE TABLE IF NOT EXISTS sap_raw.py_cluster_result (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  seqnr varchar(5) NOT NULL,
  inper varchar(6) NOT NULL,
  fpper varchar(6) NOT NULL,
  paydt date NOT NULL,
  waers varchar(5),
  gross_amount numeric(18,2),
  net_amount numeric(18,2),
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PCL2_B2_PAYROLL',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, seqnr)
);

CREATE TABLE IF NOT EXISTS sap_raw.py_cluster_rt (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  seqnr varchar(5) NOT NULL,
  lgart varchar(4) NOT NULL,
  betrg numeric(18,2),
  anzhl numeric(12,2),
  waers varchar(5),
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PAYROLL_RT',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, seqnr, lgart)
);

CREATE TABLE IF NOT EXISTS sap_raw.py_cluster_wagetype_trace (
  mandt varchar(3) NOT NULL,
  pernr varchar(8) NOT NULL,
  seqnr varchar(5) NOT NULL,
  lgart varchar(4) NOT NULL,
  rule_id varchar(10) NOT NULL,
  step_sequence integer NOT NULL,
  operation text,
  input_amount numeric(18,2),
  output_amount numeric(18,2),
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PAYROLL_TRACE',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, pernr, seqnr, lgart, rule_id, step_sequence)
);

CREATE TABLE IF NOT EXISTS sap_raw.tem_course_type (
  mandt varchar(3) NOT NULL,
  objid varchar(8) NOT NULL,
  begda date NOT NULL,
  endda date NOT NULL,
  short varchar(40),
  stext varchar(120),
  parid varchar(8),
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'TEM_HRP1000_D',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, objid, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.tem_event (
  mandt varchar(3) NOT NULL,
  objid varchar(8) NOT NULL,
  begda date NOT NULL,
  endda date NOT NULL,
  evtyp varchar(1),
  location varchar(8),
  capacity integer,
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'TEM_HRP1000_E',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, objid, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.tem_booking (
  mandt varchar(3) NOT NULL,
  eveid varchar(8) NOT NULL,
  parid varchar(8) NOT NULL,
  seqnr varchar(3) NOT NULL DEFAULT '001',
  begda date NOT NULL,
  endda date NOT NULL,
  priox varchar(1),
  bstat varchar(1),
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'PAD25_HRP1001_025',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, eveid, parid, seqnr, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.tem_resource (
  mandt varchar(3) NOT NULL,
  objid varchar(8) NOT NULL,
  otype varchar(2) NOT NULL,
  begda date NOT NULL,
  endda date NOT NULL,
  short varchar(40),
  stext varchar(120),
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'TEM_HRP1000_G_R',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, objid, otype, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.talent_appraisal_template (
  mandt varchar(3) NOT NULL,
  template_id varchar(12) NOT NULL,
  version varchar(4) NOT NULL DEFAULT '0001',
  begda date NOT NULL,
  endda date NOT NULL,
  title varchar(120),
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'TALENT_HAP_TEMPLATE',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, template_id, version, begda, endda)
);

CREATE TABLE IF NOT EXISTS sap_raw.talent_appraisal_doc (
  mandt varchar(3) NOT NULL,
  appraisal_id varchar(16) NOT NULL,
  pernr varchar(8) NOT NULL,
  appraiser_pernr varchar(8),
  begda date NOT NULL,
  endda date NOT NULL,
  apstatus varchar(2),
  final_rating varchar(4),
  final_score numeric(6,2),
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'TALENT_HAP_DOCUMENT',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, appraisal_id)
);

CREATE TABLE IF NOT EXISTS sap_raw.talent_goal_extract (
  mandt varchar(3) NOT NULL,
  goal_id varchar(16) NOT NULL,
  pernr varchar(8) NOT NULL,
  cycle_id varchar(8) NOT NULL,
  begda date NOT NULL,
  endda date NOT NULL,
  weight numeric(5,2),
  status varchar(2),
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'TALENT_GOALS_EXTRACT',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, goal_id, pernr, cycle_id)
);

CREATE TABLE IF NOT EXISTS sap_raw.talent_succession_extract (
  mandt varchar(3) NOT NULL,
  nomination_id varchar(16) NOT NULL,
  position_objid varchar(8) NOT NULL,
  candidate_pernr varchar(8) NOT NULL,
  begda date NOT NULL,
  endda date NOT NULL,
  readiness varchar(2),
  ranking integer,
  _source_system varchar(100) NOT NULL,
  _source_table varchar(30) NOT NULL DEFAULT 'TALENT_SUCCESSION_EXTRACT',
  _source_key text NOT NULL,
  _payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  _extract_ts timestamptz,
  _load_ts timestamptz NOT NULL DEFAULT now(),
  _record_hash text,
  _sync_run_id uuid,
  _valid_record boolean NOT NULL DEFAULT true,
  PRIMARY KEY (mandt, nomination_id)
);

