-- ============================================================================
-- 03_hcm_core.sql
-- Enterprise HCM Experience Platform: Canonical Normalized Core Business Entities
-- Domains: PA, OM, PT, PY, Training & Event Management, Talent & Performance
-- Includes: Relationships, Constraints, Effective Dating, Audit Fields,
--           Source-System Lineage, and Synchronization Fields.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- PA (Personnel Administration)
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS hcm_core.person (
  id uuid PRIMARY KEY,
  pernr varchar(8) UNIQUE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  birth_name text,
  birth_date date,
  gender text CHECK (gender IN ('M', 'F', 'O', 'UNKNOWN')),
  marital_status text CHECK (marital_status IN ('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'OTHER')),
  nationality text,
  national_id text,
  tax_id text,
  social_security_number text,
  blood_type text,
  -- Effective dating
  valid_from date NOT NULL DEFAULT '1800-01-01',
  valid_to date NOT NULL DEFAULT '9999-12-31',
  -- Source-system fields
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PA0002',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  -- Audit fields
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID' CHECK (data_status IN ('VALID', 'PENDING_VERIFICATION', 'INACTIVE', 'ARCHIVED')),
  is_deleted boolean NOT NULL DEFAULT false,
  -- Synchronization fields
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED' CHECK (sync_status IN ('SYNCED', 'PENDING', 'FAILED', 'RECONCILED')),
  sync_run_id uuid,
  CONSTRAINT chk_person_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.employee (
  id uuid PRIMARY KEY,
  person_id uuid NOT NULL REFERENCES hcm_core.person(id),
  pernr varchar(8) NOT NULL,
  employment_status text NOT NULL CHECK (employment_status IN ('ACTIVE', 'RETIRED', 'TERMINATED', 'SUSPENDED', 'ON_LEAVE')),
  hire_date date NOT NULL,
  original_hire_date date,
  probation_end_date date,
  termination_date date,
  company_code text NOT NULL,
  personnel_area text NOT NULL,
  personnel_subarea text,
  employee_group text NOT NULL,
  employee_subgroup text,
  cost_center text,
  -- Effective dating
  valid_from date NOT NULL DEFAULT '1800-01-01',
  valid_to date NOT NULL DEFAULT '9999-12-31',
  -- Source-system fields
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PA0000',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  -- Audit fields
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID' CHECK (data_status IN ('VALID', 'PENDING_VERIFICATION', 'INACTIVE', 'ARCHIVED')),
  is_deleted boolean NOT NULL DEFAULT false,
  -- Synchronization fields
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED' CHECK (sync_status IN ('SYNCED', 'PENDING', 'FAILED', 'RECONCILED')),
  sync_run_id uuid,
  CONSTRAINT chk_employee_dates CHECK (valid_from <= valid_to),
  CONSTRAINT uq_employee_source UNIQUE (source_system, source_key, valid_from, valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.employment_status_history (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  action_type text NOT NULL,
  action_reason text,
  employment_status text NOT NULL,
  customer_status text,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PA0000',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_status_history_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.employee_org_assignment (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  company_code text NOT NULL,
  personnel_area text NOT NULL,
  personnel_subarea text,
  employee_group text NOT NULL,
  employee_subgroup text,
  cost_center text,
  business_area text,
  payroll_area text,
  org_unit_id text NOT NULL,
  position_id text NOT NULL,
  job_id text,
  supervisor_pernr text,
  administrator_pa text,
  administrator_time text,
  administrator_payroll text,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PA0001',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_org_assign_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.employee_address (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  address_type text NOT NULL CHECK (address_type IN ('PERMANENT', 'TEMPORARY', 'EMERGENCY', 'MAILING', 'HOME')),
  street text NOT NULL,
  house_number text,
  second_address_line text,
  city text NOT NULL,
  postal_code text NOT NULL,
  state_region text,
  country text NOT NULL,
  telephone text,
  mobile_phone text,
  email_personal text,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PA0006',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_address_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.employee_family (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  relationship_type text NOT NULL CHECK (relationship_type IN ('SPOUSE', 'CHILD', 'PARENT', 'SIBLING', 'OTHER')),
  first_name text NOT NULL,
  last_name text NOT NULL,
  birth_date date,
  gender text CHECK (gender IN ('M', 'F', 'O', 'UNKNOWN')),
  national_id text,
  is_dependent boolean NOT NULL DEFAULT false,
  is_student boolean DEFAULT false,
  has_disability boolean DEFAULT false,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PA0021',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_family_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.employee_education (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  education_level text NOT NULL,
  degree_title text,
  field_of_study text,
  institution text NOT NULL,
  country text,
  grade_gpa numeric(4,2),
  graduation_date date,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PA0022',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_education_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.employee_qualification (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  qualification_code text NOT NULL,
  qualification_name text NOT NULL,
  proficiency_level text,
  obtained_date date,
  expiry_date date,
  certifying_body text,
  certificate_number text,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PA0024',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_qualification_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.employee_date_specification (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  date_type text NOT NULL,
  date_description text,
  specified_date date NOT NULL,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PA0041',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_date_spec_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.employee_contract (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  contract_type text NOT NULL,
  contract_number text,
  start_date date NOT NULL,
  end_date date,
  probation_period_months integer CHECK (probation_period_months >= 0),
  notice_period_days integer CHECK (notice_period_days >= 0),
  work_permit_number text,
  work_permit_expiry date,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PA0016',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_contract_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.employee_health_profile (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  examination_type text NOT NULL,
  examination_date date NOT NULL,
  medical_result text CHECK (medical_result IN ('FIT', 'FIT_WITH_RESTRICTIONS', 'UNFIT', 'PENDING')),
  restriction_notes text,
  next_checkup_date date,
  physician_name text,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PA0028',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_health_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.employee_disciplinary_record (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  incident_date date NOT NULL,
  action_type text NOT NULL,
  reason text NOT NULL,
  issuing_authority text,
  sanction_duration_days integer CHECK (sanction_duration_days >= 0),
  expiry_date date,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PA_DISCIPLINE_EXTRACT',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_discipline_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.employee_award (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  award_name text NOT NULL,
  award_category text,
  issued_date date NOT NULL,
  awarding_body text,
  description text,
  monetary_value numeric(18,2) CHECK (monetary_value >= 0),
  currency text DEFAULT 'EUR',
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PA_AWARD_EXTRACT',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_award_dates CHECK (valid_from <= valid_to)
);

-- ----------------------------------------------------------------------------
-- OM (Organizational Management)
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS hcm_core.om_object (
  id uuid PRIMARY KEY,
  otype varchar(2) NOT NULL CHECK (otype IN ('O', 'S', 'C', 'P', 'T', 'K', 'Q', 'D', 'E', 'L', 'G', 'R')),
  objid varchar(8) NOT NULL,
  short_code text NOT NULL,
  long_name text NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'PLANNED', 'SUBMITTED', 'APPROVED', 'REJECTED', 'HISTORICAL')),
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'HRP1000',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_om_object_dates CHECK (valid_from <= valid_to),
  CONSTRAINT uq_om_object_key UNIQUE (otype, objid, valid_from, valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.om_relationship (
  id uuid PRIMARY KEY,
  source_otype varchar(2) NOT NULL,
  source_objid varchar(8) NOT NULL,
  rsign varchar(1) NOT NULL CHECK (rsign IN ('A', 'B')),
  relat varchar(3) NOT NULL,
  target_otype varchar(2) NOT NULL,
  target_objid varchar(8) NOT NULL,
  priority varchar(2) DEFAULT '01',
  percentage numeric(5,2) DEFAULT 100.00 CHECK (percentage >= 0 AND percentage <= 100),
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'HRP1001',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_om_rel_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.org_unit_detail (
  id uuid PRIMARY KEY,
  om_object_id uuid NOT NULL REFERENCES hcm_core.om_object(id),
  org_unit_id varchar(8) NOT NULL,
  parent_org_unit_id varchar(8),
  cost_center text,
  company_code text,
  manager_pernr text,
  hierarchy_level integer DEFAULT 1,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'HRP1000_O',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_org_unit_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.position_detail (
  id uuid PRIMARY KEY,
  om_object_id uuid NOT NULL REFERENCES hcm_core.om_object(id),
  position_id varchar(8) NOT NULL,
  job_id varchar(8),
  org_unit_id varchar(8) NOT NULL,
  is_chief_position boolean NOT NULL DEFAULT false,
  is_vacant boolean NOT NULL DEFAULT false,
  planned_fte numeric(4,2) DEFAULT 1.00 CHECK (planned_fte >= 0),
  occupied_fte numeric(4,2) DEFAULT 0.00 CHECK (occupied_fte >= 0),
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'HRP1000_S',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_position_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.job_detail (
  id uuid PRIMARY KEY,
  om_object_id uuid NOT NULL REFERENCES hcm_core.om_object(id),
  job_id varchar(8) NOT NULL,
  job_family text,
  job_function text,
  standard_description text,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'HRP1000_C',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_job_dates CHECK (valid_from <= valid_to)
);

-- ----------------------------------------------------------------------------
-- PT (Personnel Time Management)
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS hcm_core.employee_work_schedule (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  schedule_code text NOT NULL,
  schedule_name text,
  employment_percentage numeric(5,2) DEFAULT 100.00 CHECK (employment_percentage > 0 AND employment_percentage <= 100),
  daily_hours numeric(5,2) CHECK (daily_hours >= 0),
  weekly_hours numeric(5,2) CHECK (weekly_hours >= 0),
  monthly_hours numeric(6,2) CHECK (monthly_hours >= 0),
  working_days_per_week numeric(3,1) CHECK (working_days_per_week >= 0 AND working_days_per_week <= 7),
  time_management_status text,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PA0007',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_schedule_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.time_absence (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  absence_type text NOT NULL,
  absence_name text,
  start_date date NOT NULL,
  end_date date NOT NULL,
  start_time time,
  end_time time,
  absence_days numeric(6,2) NOT NULL CHECK (absence_days >= 0),
  absence_hours numeric(6,2) NOT NULL CHECK (absence_hours >= 0),
  payroll_days numeric(6,2) DEFAULT 0,
  payroll_hours numeric(6,2) DEFAULT 0,
  approval_status text NOT NULL DEFAULT 'APPROVED' CHECK (approval_status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED')),
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PA2001',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_absence_dates CHECK (start_date <= end_date)
);

CREATE TABLE IF NOT EXISTS hcm_core.time_attendance (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  attendance_type text NOT NULL,
  attendance_name text,
  start_date date NOT NULL,
  end_date date NOT NULL,
  start_time time,
  end_time time,
  attendance_hours numeric(6,2) NOT NULL CHECK (attendance_hours >= 0),
  overtime_flag boolean NOT NULL DEFAULT false,
  approval_status text NOT NULL DEFAULT 'APPROVED' CHECK (approval_status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED')),
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PA2002',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_attendance_dates CHECK (start_date <= end_date)
);

CREATE TABLE IF NOT EXISTS hcm_core.time_event (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  event_timestamp timestamptz NOT NULL,
  event_type text NOT NULL CHECK (event_type IN ('CLOCK_IN', 'CLOCK_OUT', 'BREAK_START', 'BREAK_END', 'MISSION_START', 'MISSION_END')),
  terminal_id text,
  location text,
  correction_status text DEFAULT 'ORIGINAL' CHECK (correction_status IN ('ORIGINAL', 'CORRECTED', 'MANUAL_ENTRY')),
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'TEVEN',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid
);

CREATE TABLE IF NOT EXISTS hcm_core.time_quota (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  quota_type text NOT NULL,
  quota_name text,
  unit text NOT NULL DEFAULT 'DAYS' CHECK (unit IN ('DAYS', 'HOURS')),
  entitlement numeric(8,2) NOT NULL CHECK (entitlement >= 0),
  consumed numeric(8,2) NOT NULL DEFAULT 0.00 CHECK (consumed >= 0),
  remaining numeric(8,2) NOT NULL CHECK (remaining >= -100),
  deduction_from date NOT NULL,
  deduction_to date NOT NULL,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PA2006',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_quota_dates CHECK (valid_from <= valid_to),
  CONSTRAINT chk_quota_deduction_dates CHECK (deduction_from <= deduction_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.time_quota_deduction (
  id uuid PRIMARY KEY,
  time_quota_id uuid NOT NULL REFERENCES hcm_core.time_quota(id),
  time_absence_id uuid NOT NULL REFERENCES hcm_core.time_absence(id),
  deducted_amount numeric(8,2) NOT NULL CHECK (deducted_amount > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PA2006_DEDUCTION',
  source_key text NOT NULL,
  last_sync_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS hcm_core.monthly_time_summary (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  year_month varchar(7) NOT NULL,
  planned_hours numeric(7,2) NOT NULL DEFAULT 0 CHECK (planned_hours >= 0),
  actual_hours numeric(7,2) NOT NULL DEFAULT 0 CHECK (actual_hours >= 0),
  overtime_hours numeric(6,2) NOT NULL DEFAULT 0 CHECK (overtime_hours >= 0),
  absence_hours numeric(6,2) NOT NULL DEFAULT 0 CHECK (absence_hours >= 0),
  deficit_hours numeric(6,2) NOT NULL DEFAULT 0 CHECK (deficit_hours >= 0),
  evaluation_status text NOT NULL DEFAULT 'FINAL' CHECK (evaluation_status IN ('PROVISIONAL', 'FINAL', 'RECALCULATED')),
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'TIME_EVAL_B2',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT uq_monthly_time UNIQUE (employee_id, year_month)
);

-- ----------------------------------------------------------------------------
-- PY (Payroll)
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS hcm_core.pay_basic (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  pay_scale_type text,
  pay_scale_area text,
  pay_scale_group text,
  pay_scale_level text,
  capacity_utilization numeric(5,2) DEFAULT 100.00 CHECK (capacity_utilization >= 0),
  currency text NOT NULL DEFAULT 'EUR',
  basic_salary numeric(18,2) NOT NULL CHECK (basic_salary >= 0),
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PA0008',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_pay_basic_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.pay_wage_type_master (
  id uuid PRIMARY KEY,
  wage_type text NOT NULL UNIQUE,
  description_en text NOT NULL,
  description_fa text,
  category text NOT NULL CHECK (category IN ('BASE_PAY', 'ALLOWANCE', 'BONUS', 'OVERTIME', 'STATUTORY_DEDUCTION', 'VOLUNTARY_DEDUCTION', 'EMPLOYER_CONTRIBUTION', 'TAX', 'STATISTICAL')),
  is_taxable boolean NOT NULL DEFAULT false,
  is_social_security boolean NOT NULL DEFAULT false,
  calculation_rule text,
  valid_from date NOT NULL DEFAULT '1800-01-01',
  valid_to date NOT NULL DEFAULT '9999-12-31',
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'T512W',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_wage_master_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.pay_recurring (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  wage_type text NOT NULL,
  amount numeric(18,2) NOT NULL CHECK (amount >= 0),
  currency text NOT NULL DEFAULT 'EUR',
  frequency text DEFAULT 'MONTHLY' CHECK (frequency IN ('MONTHLY', 'BI_WEEKLY', 'QUARTERLY', 'ANNUAL')),
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PA0014',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_recurring_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.pay_additional (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  wage_type text NOT NULL,
  amount numeric(18,2) NOT NULL CHECK (amount >= 0),
  currency text NOT NULL DEFAULT 'EUR',
  payment_date date NOT NULL,
  reason text,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PA0015',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_additional_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.employee_loan (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  loan_type text NOT NULL,
  contract_number text NOT NULL,
  principal_amount numeric(18,2) NOT NULL CHECK (principal_amount > 0),
  repayment_amount_per_period numeric(18,2) NOT NULL CHECK (repayment_amount_per_period > 0),
  balance_amount numeric(18,2) NOT NULL CHECK (balance_amount >= 0),
  interest_rate numeric(5,2) DEFAULT 0.00 CHECK (interest_rate >= 0),
  currency text NOT NULL DEFAULT 'EUR',
  start_date date NOT NULL,
  end_date date,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PA0045',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_loan_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.payroll_period (
  id uuid PRIMARY KEY,
  fiscal_year integer NOT NULL,
  period_number integer NOT NULL,
  period_start date NOT NULL,
  period_end date NOT NULL,
  payment_date date NOT NULL,
  status text NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'RUNNING', 'LOCKED', 'CLOSED', 'ARCHIVED')),
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'T549Q',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_period_dates CHECK (period_start <= period_end),
  CONSTRAINT uq_payroll_period UNIQUE (fiscal_year, period_number)
);

CREATE TABLE IF NOT EXISTS hcm_core.payroll_result (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  payroll_period_id uuid NOT NULL REFERENCES hcm_core.payroll_period(id),
  seqnr text NOT NULL,
  gross_amount numeric(18,2) NOT NULL CHECK (gross_amount >= 0),
  statutory_deductions numeric(18,2) NOT NULL DEFAULT 0 CHECK (statutory_deductions >= 0),
  voluntary_deductions numeric(18,2) NOT NULL DEFAULT 0 CHECK (voluntary_deductions >= 0),
  total_deductions numeric(18,2) NOT NULL CHECK (total_deductions >= 0),
  net_amount numeric(18,2) NOT NULL CHECK (net_amount >= 0),
  employer_cost numeric(18,2) NOT NULL DEFAULT 0 CHECK (employer_cost >= 0),
  currency text NOT NULL DEFAULT 'EUR',
  payment_method text DEFAULT 'BANK_TRANSFER',
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PCL2_B2_PAYROLL',
  source_key text NOT NULL,
  source_cluster text DEFAULT 'CU',
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT uq_payroll_result_seq UNIQUE (employee_id, payroll_period_id, seqnr)
);

CREATE TABLE IF NOT EXISTS hcm_core.payroll_wage_type_result (
  id uuid PRIMARY KEY,
  payroll_result_id uuid NOT NULL REFERENCES hcm_core.payroll_result(id),
  wage_type text NOT NULL,
  amount numeric(18,2) NOT NULL,
  rate numeric(12,4),
  number_hours numeric(12,2),
  currency text NOT NULL DEFAULT 'EUR',
  category text NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PAYROLL_RT',
  source_key text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS hcm_core.payroll_calculation_trace (
  id uuid PRIMARY KEY,
  payroll_result_id uuid NOT NULL REFERENCES hcm_core.payroll_result(id),
  wage_type text NOT NULL,
  calculation_rule text NOT NULL,
  step_sequence integer NOT NULL,
  operation_code text,
  formula_expression text,
  input_value numeric(18,2),
  output_value numeric(18,2),
  trace_notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ----------------------------------------------------------------------------
-- Training & Event Management (TEM / LSO)
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS hcm_core.training_course_group (
  id uuid PRIMARY KEY,
  group_code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  parent_group_id uuid REFERENCES hcm_core.training_course_group(id),
  valid_from date NOT NULL DEFAULT '1800-01-01',
  valid_to date NOT NULL DEFAULT '9999-12-31',
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'TEM_HRP1000_L',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid
);

CREATE TABLE IF NOT EXISTS hcm_core.training_course (
  id uuid PRIMARY KEY,
  course_group_id uuid REFERENCES hcm_core.training_course_group(id),
  course_code text NOT NULL UNIQUE,
  title text NOT NULL,
  description text,
  learning_objectives text,
  duration_hours numeric(8,2) NOT NULL CHECK (duration_hours > 0),
  delivery_method text NOT NULL DEFAULT 'CLASSROOM' CHECK (delivery_method IN ('CLASSROOM', 'E_LEARNING', 'VIRTUAL_CLASS', 'HYBRID')),
  mandatory_for_roles text,
  status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('PLANNED', 'ACTIVE', 'RETIRED', 'LOCKED')),
  valid_from date NOT NULL DEFAULT '1800-01-01',
  valid_to date NOT NULL DEFAULT '9999-12-31',
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'TEM_HRP1000_D',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_course_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.training_event (
  id uuid PRIMARY KEY,
  course_id uuid NOT NULL REFERENCES hcm_core.training_course(id),
  event_code text NOT NULL UNIQUE,
  start_at timestamptz NOT NULL,
  end_at timestamptz NOT NULL,
  location text NOT NULL,
  room text,
  instructor_name text,
  instructor_pernr text,
  min_capacity integer DEFAULT 1 CHECK (min_capacity >= 0),
  max_capacity integer NOT NULL CHECK (max_capacity > 0),
  current_attendees integer NOT NULL DEFAULT 0 CHECK (current_attendees >= 0),
  fee_per_attendee numeric(12,2) DEFAULT 0.00 CHECK (fee_per_attendee >= 0),
  currency text DEFAULT 'EUR',
  status text NOT NULL DEFAULT 'SCHEDULED' CHECK (status IN ('PLANNED', 'SCHEDULED', 'CONFIRMED', 'CANCELLED', 'COMPLETED')),
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'TEM_HRP1000_E',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_event_dates CHECK (start_at <= end_at),
  CONSTRAINT chk_event_valid_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.training_booking (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  training_event_id uuid NOT NULL REFERENCES hcm_core.training_event(id),
  booking_date timestamptz NOT NULL DEFAULT now(),
  priority text DEFAULT 'STANDARD' CHECK (priority IN ('LOW', 'STANDARD', 'HIGH', 'MANDATORY')),
  booking_status text NOT NULL DEFAULT 'CONFIRMED' CHECK (booking_status IN ('WAITLISTED', 'CONFIRMED', 'CANCELLED', 'REBOOKED')),
  approval_status text NOT NULL DEFAULT 'APPROVED' CHECK (approval_status IN ('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'NOT_REQUIRED')),
  approved_by text,
  cancellation_reason text,
  cost numeric(12,2) DEFAULT 0.00 CHECK (cost >= 0),
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'PAD25_HRP1001_025',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT uq_employee_event_booking UNIQUE (employee_id, training_event_id)
);

CREATE TABLE IF NOT EXISTS hcm_core.training_attendance_result (
  id uuid PRIMARY KEY,
  booking_id uuid NOT NULL REFERENCES hcm_core.training_booking(id),
  attended boolean NOT NULL DEFAULT false,
  completion_status text NOT NULL DEFAULT 'COMPLETED' CHECK (completion_status IN ('COMPLETED', 'INCOMPLETE', 'FAILED', 'PASSED')),
  score numeric(5,2) CHECK (score >= 0 AND score <= 100),
  certificate_number text,
  issue_date date,
  valid_until date,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'TEM_RESULTS',
  source_key text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS hcm_core.employee_qualification_gap (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  position_id text NOT NULL,
  qualification_code text NOT NULL,
  qualification_name text NOT NULL,
  required_level text NOT NULL,
  actual_level text,
  gap_status text NOT NULL CHECK (gap_status IN ('MATCHED', 'DEFICIT', 'EXCEEDED', 'SURPLUS')),
  recommended_course_id uuid REFERENCES hcm_core.training_course(id),
  evaluated_at timestamptz NOT NULL DEFAULT now(),
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'QUALIFICATION_GAP_EVAL',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid
);

-- ----------------------------------------------------------------------------
-- Talent & Performance Management
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS hcm_core.performance_cycle (
  id uuid PRIMARY KEY,
  cycle_code text NOT NULL UNIQUE,
  name text NOT NULL,
  cycle_type text NOT NULL CHECK (cycle_type IN ('ANNUAL', 'MID_YEAR', 'QUARTERLY', 'PROJECT')),
  start_date date NOT NULL,
  end_date date NOT NULL,
  self_assessment_deadline date,
  manager_review_deadline date,
  status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('PLANNED', 'ACTIVE', 'IN_CALIBRATION', 'CLOSED', 'ARCHIVED')),
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'TALENT_CYCLES',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_cycle_dates CHECK (start_date <= end_date)
);

CREATE TABLE IF NOT EXISTS hcm_core.employee_goal (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  performance_cycle_id uuid NOT NULL REFERENCES hcm_core.performance_cycle(id),
  goal_code text NOT NULL,
  title text NOT NULL,
  description text,
  metric_target text,
  weight numeric(5,2) NOT NULL DEFAULT 10.00 CHECK (weight >= 0 AND weight <= 100),
  progress_percentage numeric(5,2) NOT NULL DEFAULT 0.00 CHECK (progress_percentage >= 0 AND progress_percentage <= 100),
  status text NOT NULL DEFAULT 'IN_PROGRESS' CHECK (status IN ('DRAFT', 'APPROVED', 'IN_PROGRESS', 'COMPLETED', 'DEFERRED', 'CANCELLED')),
  employee_comment text,
  manager_comment text,
  target_completion_date date,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'TALENT_GOALS_EXTRACT',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_goal_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.performance_document (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  performance_cycle_id uuid NOT NULL REFERENCES hcm_core.performance_cycle(id),
  appraiser_pernr text,
  document_status text NOT NULL DEFAULT 'IN_PROGRESS' CHECK (document_status IN ('DRAFT', 'SELF_ASSESSMENT', 'MANAGER_REVIEW', 'CALIBRATION', 'COMPLETED', 'ARCHIVED')),
  self_rating text,
  manager_rating text,
  calibrated_rating text,
  overall_score numeric(5,2) CHECK (overall_score >= 0 AND overall_score <= 100),
  promotion_readiness text CHECK (promotion_readiness IN ('NOT_READY', 'WITHIN_1_YEAR', 'READY_NOW', 'HIGH_POTENTIAL')),
  retention_risk text CHECK (retention_risk IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
  impact_of_loss text CHECK (impact_of_loss IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'TALENT_HAP_DOCUMENT',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_perf_doc_dates CHECK (valid_from <= valid_to),
  CONSTRAINT uq_perf_doc UNIQUE (employee_id, performance_cycle_id)
);

CREATE TABLE IF NOT EXISTS hcm_core.competency_master (
  id uuid PRIMARY KEY,
  competency_code text NOT NULL UNIQUE,
  name text NOT NULL,
  category text NOT NULL CHECK (category IN ('CORE', 'LEADERSHIP', 'FUNCTIONAL', 'TECHNICAL')),
  description text,
  valid_from date NOT NULL DEFAULT '1800-01-01',
  valid_to date NOT NULL DEFAULT '9999-12-31',
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'HRP1000_Q',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid
);

CREATE TABLE IF NOT EXISTS hcm_core.competency_assessment (
  id uuid PRIMARY KEY,
  performance_document_id uuid NOT NULL REFERENCES hcm_core.performance_document(id),
  competency_id uuid NOT NULL REFERENCES hcm_core.competency_master(id),
  self_rating numeric(3,1) CHECK (self_rating >= 1 AND self_rating <= 5),
  manager_rating numeric(3,1) CHECK (manager_rating >= 1 AND manager_rating <= 5),
  calibrated_rating numeric(3,1) CHECK (calibrated_rating >= 1 AND calibrated_rating <= 5),
  comments text,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'TALENT_HAP_COMPETENCY',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid
);

CREATE TABLE IF NOT EXISTS hcm_core.development_plan (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  action_code text NOT NULL,
  title text NOT NULL,
  description text,
  development_type text NOT NULL CHECK (development_type IN ('ON_THE_JOB', 'FORMAL_TRAINING', 'MENTORING', 'PROJECT_ASSIGNMENT')),
  linked_competency_id uuid REFERENCES hcm_core.competency_master(id),
  target_date date NOT NULL,
  actual_date date,
  status text NOT NULL DEFAULT 'IN_PROGRESS' CHECK (status IN ('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
  mentor_name text,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'TALENT_IDP_EXTRACT',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_idp_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.career_aspiration (
  id uuid PRIMARY KEY,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  target_role text NOT NULL,
  timeframe_years integer DEFAULT 2 CHECK (timeframe_years >= 0),
  willing_to_relocate boolean DEFAULT false,
  mobility_preference text,
  notes text,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'TALENT_CAREER_EXTRACT',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_career_dates CHECK (valid_from <= valid_to)
);

CREATE TABLE IF NOT EXISTS hcm_core.succession_candidate (
  id uuid PRIMARY KEY,
  position_source_key text NOT NULL,
  target_position_id text,
  employee_id uuid NOT NULL REFERENCES hcm_core.employee(id),
  readiness_level text NOT NULL CHECK (readiness_level IN ('EMERGENCY', 'READY_NOW', 'READY_1_2_YEARS', 'READY_3_5_YEARS')),
  ranking integer DEFAULT 1 CHECK (ranking > 0),
  is_nominated_by_executive boolean DEFAULT false,
  risk_of_departure text CHECK (risk_of_departure IN ('LOW', 'MEDIUM', 'HIGH')),
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_system text NOT NULL DEFAULT 'SAP_S4HANA',
  source_object text NOT NULL DEFAULT 'TALENT_SUCCESSION_EXTRACT',
  source_key text NOT NULL,
  source_version text DEFAULT '1.0',
  source_valid_from date,
  source_valid_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text DEFAULT 'SYSTEM',
  updated_by text DEFAULT 'SYSTEM',
  data_status text NOT NULL DEFAULT 'VALID',
  is_deleted boolean NOT NULL DEFAULT false,
  last_sync_at timestamptz DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'SYNCED',
  sync_run_id uuid,
  CONSTRAINT chk_succession_dates CHECK (valid_from <= valid_to)
);
